
local function AddWikiLib(name)
	LUABEE.AddLibrary(name, Color(0,0,0))
	LUABEE.AddWikiCategory("Libraries", name)
end
local function AddWikiClass(name)
	LUABEE.AddClass(name, Color(0,0,0))
	LUABEE.AddWikiCategory("Classes", name)
end
local function AddWikiHook(name)
	LUABEE.AddHook(name, Color(0,0,0))
	LUABEE.AddWikiCategory("Hooks", name)
end

AddWikiLib("drive")
AddWikiLib("duplicator")
AddWikiLib("effects")
AddWikiLib("engine")
AddWikiLib("ents")
AddWikiLib("file")
AddWikiLib("frame_blend")
AddWikiLib("game")
AddWikiLib("gameevent")
AddWikiLib("gamemode")
AddWikiLib("gmod")
AddWikiLib("gmsave")
AddWikiLib("gui")
AddWikiLib("GWEN")
AddWikiLib("halo")
AddWikiLib("hammer")
AddWikiLib("http")
AddWikiLib("input")
AddWikiLib("jit")
AddWikiLib("killicon")
AddWikiLib("language")
AddWikiLib("list")
AddWikiLib("markup")
AddWikiLib("math")
AddWikiLib("motionsensor")
AddWikiLib("navmesh")
AddWikiLib("net")
AddWikiLib("notification")
AddWikiLib("numpad")
AddWikiLib("os")
AddWikiLib("package")
AddWikiLib("physenv")
AddWikiLib("player_manager")
AddWikiLib("player")
AddWikiLib("presets")
AddWikiLib("properties")
AddWikiLib("render")
AddWikiLib("resource")
AddWikiLib("saverestore")
AddWikiLib("scripted_ents")
AddWikiLib("search")
AddWikiLib("sound")
AddWikiLib("spawnmenu")
AddWikiLib("sql")
AddWikiLib("steamworks")
AddWikiLib("string")
AddWikiLib("surface")
AddWikiLib("system")
AddWikiLib("team")
AddWikiLib("umsg")
AddWikiLib("undo")
AddWikiLib("usermessage")
AddWikiLib("video")

-------------------------------------------------------------------------------

AddWikiClass("bf_read")
AddWikiClass("BotPath")
AddWikiClass("CEffectData")
AddWikiClass("CLuaEmitter")
AddWikiClass("CLuaParticle")
AddWikiClass("CMoveData")
AddWikiClass("ConVar")
AddWikiClass("CRecipientFilter")
AddWikiClass("CSEnt")
AddWikiClass("CSoundPatch")
AddWikiClass("CTakeDamageInfo")
AddWikiClass("CUserCmd")
AddWikiClass("Entity")
AddWikiClass("File")
AddWikiClass("IGModAudioChannel")
AddWikiClass("IMaterial")
AddWikiClass("IMesh")
AddWikiClass("IRestore")
AddWikiClass("ISave")
AddWikiClass("ITexture")
AddWikiClass("IVideoWriter")
AddWikiClass("Locomotion")
AddWikiClass("NavArea")
AddWikiClass("NextBot")
AddWikiClass("NPC")
AddWikiClass("Panel")
AddWikiClass("PhysObj")
AddWikiClass("Player")
AddWikiClass("Stack")
AddWikiClass("Vector")
AddWikiClass("Vehicle")
AddWikiClass("VMatrix")
AddWikiClass("Weapon")

-------------------------------------------------------------------------------

--Hooks are one at a time.
